# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: src/Magento/FunctionalTestingFramework
    envs: etc/_envs
settings:
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Magento\FunctionalTestingFramework\Extension\TestContextExtension
        - Magento\FunctionalTestingFramework\Allure\Adapter\MagentoAllureAdapter
        - Magento\FunctionalTestingFramework\Extension\PageReadinessExtension
    config:
        Yandex\Allure\Adapter\AllureAdapter:
            deletePreviousResults: true
            outputDirectory: allure-results
            ignoredAnnotations:
                - env
                - zephyrId
                - useCaseId
        Magento\FunctionalTestingFramework\Extension\PageReadinessExtension:
            driver: \Magento\FunctionalTestingFramework\Module\MagentoWebDriver
            timeout: 30
            resetFailureThreshold: 3
            readinessMetrics:
                - \Magento\FunctionalTestingFramework\Extension\ReadinessMetrics\DocumentReadyState
                - \Magento\FunctionalTestingFramework\Extension\ReadinessMetrics\JQueryAjaxRequests
                - \Magento\FunctionalTestingFramework\Extension\ReadinessMetrics\PrototypeAjaxRequests
                - \Magento\FunctionalTestingFramework\Extension\ReadinessMetrics\RequireJsDefinitions
                - \Magento\FunctionalTestingFramework\Extension\ReadinessMetrics\MagentoLoadingMasks
params:
    - .env